### Setup Toolchains ###

# Vendor EABI (androideabi - gnueabi - <any_other>eabi)
VENDOREABI := linux-androideabi
KERNELEABI := eabi

# GCC Version Setup
TARGET_NDK_GCC_VERSION := 4.9
TARGET_GCC_VERSION := 4.9
TARGET_LEGACY_GCC_VERSION := 4.8

# Android toolchain ROOT & PREFIX
TARGET_TOOLCHAIN_ROOT := prebuilts/gcc/$(HOST_OS)-$(HOST_PREBUILT_ARCH)/$(TARGET_ARCH)/$(TARGET_ARCH)-$(VENDOREABI)-$(TARGET_GCC_VERSION)
TARGET_TOOLS_PREFIX := $(TARGET_TOOLCHAIN_ROOT)/bin/$(TARGET_ARCH)-$(VENDOREABI)-

# Android Toolchain
ANDROID_TOOLCHAIN := $(TARGET_TOOLCHAIN_ROOT)/bin

# Kernel toolchain (eabi)
ANDROID_KERNEL_TOOLCHAIN_ROOT := prebuilts/gcc/$(HOST_OS)-$(HOST_PREBUILT_ARCH)/$(TARGET_ARCH)/$(TARGET_ARCH)-$(KERNELEABI)-$(TARGET_LEGACY_GCC_VERSION)
ANDROID_KERNEL_TOOLCHAIN_PREFIX := $(ANDROID_KERNEL_TOOLCHAIN_ROOT)/bin/$(TARGET_ARCH)-$(KERNELEABI)-

# Android Kernel (arm-eabi) toolchain
ARM_EABI_TOOLCHAIN := $(ANDROID_KERNEL_TOOLCHAIN_ROOT)/bin

# Android Kernel toolchain PATH
ANDROID_KERNEL_TOOLCHAIN_PATH := $(ARM_EABI_TOOLCHAIN)

### End toolchain setup ###
